targets:
  - name: "Example Site"
    url: "https://example.com"
    method: "GET"
    headers:
      User-Agent: "Datadog-Monitor"
    labels:
      env: "production"
      service: "website"
    interval: 30
    timeout: 5
  - name: "Httpbin OK"
    url: "http://httpbin.org/status/200"
    interval: 60
    timeout: 3
    labels:
      env: "testing"
  - name: "Httpbin Error"
    url: "http://httpbin.org/status/500"
    interval: 30
    timeout: 2
    labels:
      env: "testing"
      status: "error-test"
  - name: "Slow Response"
    url: "http://httpbin.org/delay/1"
    interval: 40
    timeout: 5
    labels:
      env: "testing"
      type: "slow"
datadog:
  host: "datadog-agent"
  port: 8125
