defaults:
  method: "GET"
  interval: 60
  timeout: 10
  check_cert: true
  verify_cert: false
  headers:
    User-Agent: "Datadog-Monitor"
  labels:
    app: "url-monitor"

targets:
  - name: "Example Site"
    url: "https://example.com"
    labels:
      env: "production"
      service: "website"
    interval: 30
    timeout: 5
  - name: "Httpbin OK" 
    url: "http://httpbin.org/status/200"
    interval: 60
    timeout: 3
    check_cert: false  # Explicitly disable cert check for non-HTTPS
    labels:
      env: "testing"
  - name: "Httpbin Error"
    url: "http://httpbin.org/status/500"
    interval: 30
    timeout: 2
    check_cert: false  # Explicitly disable cert check for non-HTTPS
    labels:
      env: "testing"
      status: "error-test"
  - name: "Slow Response"
    url: "http://httpbin.org/delay/1"
    interval: 40
    timeout: 5
    check_cert: false  # Explicitly disable cert check for non-HTTPS
    labels:
      env: "testing"
      type: "slow"
  - name: "SSL Check Example"
    url: "https://google.com"
    interval: 45
    timeout: 5
    # Using defaults for cert check (enabled)
    # Verifying the certificate chain for this target
    verify_cert: true
    labels:
      env: "production"
      type: "ssl-verification"
datadog:
  host: "127.0.0.1"
  port: 8125
