{{- if eq .Values.mode "standalone" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}-config
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.standalone.config | indent 4 }}
{{- end }}