apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "url-datadog-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "url-datadog-monitor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "url-datadog-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "url-datadog-monitor.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq .Values.mode "standalone" }}
          env:
            - name: DATADOG_HOST
              value: {{ .Values.datadog.host | quote }}
            - name: DATADOG_PORT
              value: {{ .Values.datadog.port | quote }}
          args:
            - "-config=/config/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /config
          {{- else }}
          args:
            - "--dogstatsd-host={{ .Values.datadog.host }}"
            - "--dogstatsd-port={{ .Values.datadog.port }}"
            {{- if .Values.operator.leaderElection.enabled }}
            - "--leader-elect=true"
            {{- else }}
            - "--leader-elect=false"
            {{- end }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: healthz
              containerPort: 8081
              protocol: TCP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.mode "standalone" }}
      volumes:
        - name: config
          configMap:
            name: {{ include "url-datadog-monitor.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
