{{- if and (eq .Values.mode "operator") .Values.crd.rbac.create -}}
# First, create a special role for the CRD job to manage CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}-crd-job
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}-crd-job
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-15"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "url-datadog-monitor.fullname" . }}-crd-job
subjects:
  - kind: ServiceAccount
    name: {{ include "url-datadog-monitor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - urlmonitoring.kuskoman.github.com
    resources:
      - urlmonitors
      - urlmonitors/status
      - urlmonitors/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  {{- if .Values.operator.leaderElection.enabled }}
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "url-datadog-monitor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "url-datadog-monitor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
