apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-datadog-monitor.fullname" . }}
  labels:
    {{- include "url-datadog-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: healthz
      protocol: TCP
      name: healthz
  selector:
    {{- include "url-datadog-monitor.selectorLabels" . | nindent 4 }}