name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-binaries:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Set version variables
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          mkdir -p bin/release
          make cross-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/release/
          retention-days: 1

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin/release/

      - name: Set version variables
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"* %s (%h)" > CHANGELOG.md
          else
            git log --pretty=format:"* %s (%h)" $PREV_TAG..${{ github.ref }} > CHANGELOG.md
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          body: |
            ## URL Datadog Monitor ${{ env.VERSION }}

            ### Changes
            ${{ steps.changelog.outputs.changelog }}

            ### Installation

            #### Docker
            ```bash
            docker pull ghcr.io/kuskoman/url-datadog-monitor:${{ env.VERSION }}-standalone-scratch
            docker pull ghcr.io/kuskoman/url-datadog-monitor:${{ env.VERSION }}-operator-scratch
            ```

            #### Binary
            Download the appropriate binary for your platform below.
          files: |
            bin/release/*
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

  build-push-docker:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version variables
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Build and push standalone-scratch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/standalone-scratch.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          tags: |
            ghcr.io/kuskoman/url-datadog-monitor:${{ env.VERSION }}-standalone-scratch
            ghcr.io/kuskoman/url-datadog-monitor:latest-standalone-scratch
            ghcr.io/kuskoman/url-datadog-monitor:latest-standalone
            ghcr.io/kuskoman/url-datadog-monitor:latest

      - name: Build and push operator-scratch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/operator-scratch.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          tags: |
            ghcr.io/kuskoman/url-datadog-monitor:${{ env.VERSION }}-operator-scratch
            ghcr.io/kuskoman/url-datadog-monitor:latest-operator-scratch
            ghcr.io/kuskoman/url-datadog-monitor:latest-operator

      - name: Build and push standalone-alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/standalone-alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          tags: |
            ghcr.io/kuskoman/url-datadog-monitor:${{ env.VERSION }}-standalone-alpine
            ghcr.io/kuskoman/url-datadog-monitor:latest-standalone-alpine

      - name: Build and push operator-alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/operator-alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          tags: |
            ghcr.io/kuskoman/url-datadog-monitor:${{ env.VERSION }}-operator-alpine
            ghcr.io/kuskoman/url-datadog-monitor:latest-operator-alpine